openapi: 3.0.0
info:
  title: Sample API
  description: Just a simple example
  version: 0.0.1

servers:
  - url: http://api.example.net/api/
    description: Live API endpoint

paths:
  /thing:
    get:
      summary: Returns a list of things.
      description: Returns a list of things.
      responses:
        '200':
          description: A JSON array of things
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Thing'
components:
  schemas:
    Thing:
      properties:
        id:
          type: string
        title:
          type: string
      required:
        - id
        - title
