# ==========================================================================
# Example API file for use with REST Client for VS Code
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client
# ==========================================================================

@host = api.example.net
#@host = localhost:8000

### Get something
GET http://{{host}}/api/thing

### Create something
POST http://{{host}}/api/thing
content-type: application/json

{
  "title": "An example",
  "count": 66,
  "tags": [ "foobar" ]
}

### Update something
PUT http://{{host}}/api/thing/123
content-type: application/json

{
  "title": "Some new title"
}

### Delete something
DELETE http://{{host}}/api/thing/123
