name: Release Assets

# This is a generic release pipeline that assumes project is to be built as a container image
# This is triggered on a GitHub release

on:
  # Workflow runs when a release is created in GitHub
  release:
    types: [published]

env:
  IMAGE_REG: ghcr.io
  IMAGE_NAME: __CHANGE_ME__

jobs:
  release:
    name: Release image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      # Build image tagged with the release version
      - name: Build the container image
        run: make image IMAGE_REPO=$GITHUB_ACTOR/$IMAGE_NAME IMAGE_TAG=${{ github.event.release.tag_name }}

      # Push to the registry
      - name: Push to container registry
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login $IMAGE_REG -u $GITHUB_ACTOR --password-stdin
          make push IMAGE_REPO=$GITHUB_ACTOR/$IMAGE_NAME IMAGE_TAG=${{ github.event.release.tag_name }}